// Generated by insterra

module "aws_database_proxima_zvd" {
  source  = "upmaru/instellar/aws//modules/database"
  version = "0.6.3"

  db_name             = "instellardb"
  db_size             = "db.t3.small"
  db_username         = "instellar"
  deletion_protection = false
  engine              = "postgres"
  engine_version      = "15"
  identifier          = "proxima-zvd"
  port                = 5432
  security_group_ids = [
    module.aws_compute_proxima_flt.nodes_security_group_id
  ]
  skip_final_snapshot = true
  subnet_ids          = module.aws_foundation_proxima_fvb.public_subnet_ids
  vpc_id              = module.aws_foundation_proxima_fvb.vpc_id
}
