// Generated by insterra

module "aws_foundation_proxima_fvb" {
  source  = "upmaru/instellar/aws//modules/network"
  version = "0.6.3"

  identifier          = var.identifier
  public_subnet_cidrs = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  region              = var.aws_region
  vpc_ip_range        = "10.0.0.0/16"
}
