// Generated by insterra

module "instellar_link_proxima_bcj" {
  source  = "upmaru/bootstrap/instellar//modules/storage"
  version = "0.5.0"

  access_key = module.aws_storage_proxima_amw.access_key_id
  bucket     = module.aws_storage_proxima_amw.name
  host       = module.aws_storage_proxima_amw.host
  region     = var.aws_region
  secret_key = module.aws_storage_proxima_amw.secret_access_key
}

module "instellar_link_proxima_qcb" {
  source  = "upmaru/bootstrap/instellar"
  version = "0.5.0"

  bootstrap_node  = module.aws_compute_proxima_flt.bootstrap_node
  cluster_address = module.aws_compute_proxima_flt.cluster_address
  cluster_name    = module.aws_compute_proxima_flt.identifier
  nodes           = module.aws_compute_proxima_flt.nodes
  password_token  = module.aws_compute_proxima_flt.trust_token
  provider_name   = "aws"
  region          = var.aws_region

}

module "instellar_link_proxima_yvj" {
  source  = "upmaru/bootstrap/instellar//modules/service"
  version = "0.5.0"

  channels = ["develop"]
  cluster_ids = [
    module.instellar_link_proxima_qcb.cluster_id
  ]
  credential = {
    host     = module.aws_database_proxima_zvd.address
    password = module.aws_database_proxima_zvd.password
    port     = module.aws_database_proxima_zvd.port
    resource = module.aws_database_proxima_zvd.db_name
    username = module.aws_database_proxima_zvd.username
    secure   = true
  }

  driver         = "database/postgresql"
  driver_version = module.aws_database_proxima_zvd.engine_version
  provider_name  = "aws"
  slug           = module.aws_database_proxima_zvd.identifier
}
